apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tee-time-data
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage }}
